apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: thirsty-shrimp-java-springboot-gitops
  description: This is GitOps manifest for thirsty-shrimp-java-springboot   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: thirsty-shrimp-java-springboot
    janus-idp.io/tekton: thirsty-shrimp-java-springboot 
    backstage.io/kubernetes-id: thirsty-shrimp-java-springboot 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:thirsty-shrimp-java-springboot
