apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: thirsty-shrimp-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-hub/thirsty-shrimp-java-springboot-gitops